openapi: 3.0.0
info:
  title: TruckBusters API
  description: API to see disponibility of TruckBusters appointments.
  version: 0.1.9
servers:
  - url: http://truckbusters-api/v1/appointment
    description:
  - url: http://staging-api.example.com
    description: Not a true API, just a line to remember I can do more.
paths:
  /appointment:
    get:
      summary: Returns a list of appointment.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of appointment
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    start_date: 
                      type: String
                      format: date-time 
                    society:
                      type: object
                      items:
                        name:
                          type: String
                        mail:
                          type: String
                        driver: 
                          type: object
                          items:
                            firstname:  
                              type: String
                            lastname:
                              type: String
                        vehicle: 
                          type: object
                          items:
                            brand:
                              type: String
                            model:
                              type: String
                            registration_number:
                              type: String